Add HAFS license file  LICENSE.md
hafs-community/HAFS pull request #256
Opened 2024-01-29 20:28 UTC by ZhanZhang-NOAA

## Description of changes
This PR is to add a general license to HAFS repository. 

## Issues addressed (optional)
If this PR addresses issue 252, link is provided as follows.
- - fixes issue 252: https://github.com/hafs-community/HAFS/issues/252

## Dependencies (optional)
No dependencies

## Contributors (optional)
If others worked on this PR besides the author, please include their user names here (using @Mention if possible).

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

## Application-level regression test status
Require regression tests are not required since only HAFS license is added. 

Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [ ] Hera
- [ ] Orion
- [ ] WCOSS2

2024-02-06 17:45 UTC, gspetro-NOAA commented on LICENSE.md
> +- UFS: [UFS-weather-model License](https://github.com/ufs-community/ufs-weather-model/blob/develop/LICENSE.md)
```suggestion
- UFS: [ufs-weather-model License](https://github.com/ufs-community/ufs-weather-model/blob/develop/LICENSE.md)
```

2024-02-06 17:46 UTC, gspetro-NOAA commented on LICENSE.md
> +- UFS-UTILS: [UFS-UTILS Licence](https://github.com/ufs-community/UFS_UTILS/blob/develop/LICENSE.md)
```suggestion
- UFS_UTILS: [UFS_UTILS Licence](https://github.com/ufs-community/UFS_UTILS/blob/develop/LICENSE.md)
```

2024-02-06 17:47 UTC, gspetro-NOAA commented on LICENSE.md
> +- UFS-UTILS: [UFS-UTILS Licence](https://github.com/ufs-community/UFS_UTILS/blob/develop/LICENSE.md)
Alternatively, you could do:
```
- UFS Utilities: [UFS_UTILS Licence](https://github.com/ufs-community/UFS_UTILS/blob/develop/LICENSE.md)
```

2024-02-06 17:47 UTC, gspetro-NOAA commented on LICENSE.md
> +The intent of this license is to ensure free and unrestricted access to the HAFS software, and to pass on those rights to modified versions this software.
```suggestion
The intent of this license is to ensure free and unrestricted access to the HAFS software and to pass on those rights to modified versions this software.
```

2024-02-06 17:48 UTC, gspetro-NOAA commented on LICENSE.md
> +Unless required by applicable law or agreed to in writing, software distributed under the License
```suggestion
Unless required by applicable law or agreed to in writing, software distributed under this License 
```

2024-02-06 17:49 UTC, gspetro-NOAA commented
Looks good to me! Just suggested a few tiny edits.

2024-02-06 20:32 UTC, KathrynNewman requested changes
Looks good to me as well! I added a couple additional minor edits.

2024-02-06 20:32 UTC, KathrynNewman commented on LICENSE.md
> +This file is part of the Hurricane Forecast and Analysis System, referred to as HAFS, which is made available under version 3 of the Gnu Lesser General Public License.
```suggestion
This file is part of the Hurricane Analysis and Forecast System, referred to as HAFS, which is made available under version 3 of the GNU Lesser General Public License.
```

2024-03-04 15:47 UTC, BinLiu-NOAA approved these changes
Looks good to me. Thanks!

2024-03-04 15:49 UTC, AvichalMehra-NOAA commented
Approved.

2024-03-04 16:35 UTC, KathrynNewman approved these changes

2024-03-04 17:03 UTC, merged